import Head from "next/head";
import Carousal from "../components/home/Carousal";
import Hero from "../components/home/Hero";
import Stats from "../components/home/Stats";
import Navbar from "../components/common/Navbar";
import Footer from "../components/common/Footer";
import Donate from "../components/home/Donate";
import About from "../components/home/About";
import dynamic from "next/dynamic";
const Testimonials = dynamic(() => import('../components/home/Testimonials'), { ssr: false });
const CoreTeam = dynamic(() => import('../components/home/CoreTeam'), { ssr: false });


export default function Home() {
  return (
    <>
      <Head>
        <title>Shri Ravindra Gurukul</title>
        <link rel="icon" href="/logo2.png" />
        {/* Meta Tags Dynamically generated by metaseo.itsvg.in */}
        <meta name="title" content="Shri Ravindra Gurukul" />
        <meta
          name="description"
          content="We reduce the wastage of food by using it for a good cause and provide a healthy meal to kids so that they can sleep with no hunger."
        />
        <meta name="copyright" content="AshishRangdal" />

        <meta property="og:type" content="website" />
        <meta property="og:url" content="shreeravindragurukul.org" />
        <meta property="og:title" content="Shri Ravindra Gurukul" />
        <meta
          property="og:description"
          content="We reduce the wastage of food by using it for a good cause and provide a healthy meal to kids so that they can sleep with no hunger."
        />
        <meta property="og:image" content="https://shreeravindragurukul.org/og.png" />
        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:url" content="shreeravindragurukul.org" />
        <meta property="twitter:title" content="Shri Ravindra Gurukul" />
        <meta
          property="twitter:description"
          content="We reduce the wastage of food by using it for a good cause and provide a healthy meal to kids so that they can sleep with no hunger."
        />
        <meta property="twitter:image" content="https://shreeravindragurukul.org/og.png" />
      </Head>

      <main className="">
        <Navbar />
        <Hero />
        <Carousal />
        <Stats />
        <Donate />
        <Testimonials />
        <CoreTeam />
        <About />
      </main>

      <Footer />
    </>
  );
}
